"""phase3 issuers custodians assets

Revision ID: 43b2ddb8875c
Revises: 9da67ca9bb72
Create Date: 2026-08-22 00:30:33.339801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b2ddb8875c'
down_revision: Union[str, None] = '9da67ca9bb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custodian',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('ifsca_registration_no', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('ifsca_verified', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('verified_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ifsca_registration_no')
    )
    op.create_table('issuer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legal_name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('registration_jurisdiction', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='issuer_verification_status_enum'), autoincrement=False, nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('verified_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('asset_class', sa.Enum('SECURITY', 'REAL_ESTATE', 'COMMODITY', 'INFRASTRUCTURE', 'IP', name='asset_asset_class_enum'), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('custodian_verified', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('custodian_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # -- ★ manually added: the migration-level half of "an asset cannot be tokenized unless its
    # custodian is IFSCA-verified" -- see `Custodian`'s and `Asset`'s docstrings for the full
    # rationale. `austial.orm`'s `@Entity()`/`Column()`/`ManyToOne()` have no support for
    # composite unique constraints, composite foreign keys, or table-level CHECK constraints
    # (confirmed by reading `austial-py/packages/orm/src/austial/orm/decorators/{entity,column,
    # relations}.py`), so this is hand-authored DDL, not something the entity metadata could
    # express -- same "escape hatch for what `@Entity()` can't model" pattern as this file's
    # `sa.Enum(...).drop(...)` calls in `downgrade()` below.
    #
    # 1. A composite UNIQUE(id, ifsca_verified) on `custodian` -- required before it can be the
    #    target of a composite foreign key below (Postgres requires the referenced columns to be
    #    covered by a unique/primary-key constraint).
    op.create_unique_constraint('uq_custodian_id_ifsca_verified', 'custodian', ['id', 'ifsca_verified'])
    # 2. A composite FK on `asset(custodian_id, custodian_verified)` -- replaces the plain
    #    single-column `custodian_id -> custodian.id` FK autogenerate produced above (removed
    #    from the `create_table('asset', ...)` call). A single-column FK only proves *a*
    #    custodian row exists; this composite FK additionally forces whatever `custodian_verified`
    #    was written to match the *actual* `custodian.ifsca_verified` value for that row at write
    #    time -- catching any race between `AssetsService.attach_custodian`'s service-layer check
    #    and the write itself.
    op.create_foreign_key(
        'fk_asset_custodian_verified',
        'asset',
        'custodian',
        ['custodian_id', 'custodian_verified'],
        ['id', 'ifsca_verified'],
        ondelete='RESTRICT',
    )
    # 3. A CHECK constraint tying `custodian_id IS NOT NULL` to `custodian_verified = true` -- the
    #    composite FK alone doesn't rule out attaching an *unverified* custodian, since a row
    #    matching `(custodian_id, false)` always exists for any unverified custodian. This CHECK
    #    closes that gap: once `custodian_id` is set, `custodian_verified` must be `true`, and
    #    (by the FK above) that `true` must actually match the referenced custodian's real state.
    op.create_check_constraint(
        'ck_asset_custodian_verified_when_attached',
        'asset',
        'custodian_id IS NULL OR custodian_verified = true',
    )


def downgrade() -> None:
    # Manually added -- drop the hand-authored composite-constraint DDL before the autogenerated
    # `drop_table()` calls below (a table can't be dropped while it's still the target of a
    # foreign key from another table).
    op.drop_constraint('ck_asset_custodian_verified_when_attached', 'asset', type_='check')
    op.drop_constraint('fk_asset_custodian_verified', 'asset', type_='foreignkey')
    op.drop_constraint('uq_custodian_id_ifsca_verified', 'custodian', type_='unique')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    op.drop_table('issuer')
    op.drop_table('custodian')
    # ### end Alembic commands ###

    # Manually added -- see `60429c1b1184_initial_schema.py::downgrade()`'s comment for why
    # autogenerate never emits `DROP TYPE` for Postgres native `ENUM` columns. Every `EnumType`
    # column introduced by this migration's `upgrade()` needs its named enum type dropped here
    # too, or a downgrade-then-upgrade round trip fails with `DuplicateObjectError` on `CREATE
    # TYPE` the second time around.
    sa.Enum(name='issuer_verification_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='asset_asset_class_enum').drop(op.get_bind(), checkfirst=True)
