"""initial schema

Revision ID: 60429c1b1184
Revises: 
Create Date: 2026-08-21 18:41:21.874954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60429c1b1184'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('action', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('before_state', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('after_state', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.Enum('INVESTOR', 'ISSUER', 'COMPLIANCE_OFFICER', 'ADMIN', name='user_role_enum'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('investor_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kyc_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='investor_profile_kyc_status_enum'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('revoked', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_token')
    op.drop_table('investor_profile')
    op.drop_table('user')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

    # Manually added -- autogenerate's `downgrade()` for Postgres never emits `DROP TYPE` for
    # native `ENUM` columns (a documented Alembic/Postgres limitation, not an austial-orm bug):
    # `op.drop_table()` only drops the table, not the separately-created named enum type each
    # `EnumType` column above compiled to (`user_role_enum`, `investor_profile_kyc_status_enum`
    # -- see `austial-orm`'s `sqlalchemy_support.py::_sqla_column`'s `<table>_<column>_enum`
    # naming). Left as-is, a downgrade-then-upgrade round trip fails with
    # `DuplicateObjectError: type "user_role_enum" already exists` the second time `upgrade()`
    # tries `CREATE TYPE`. Drop them explicitly here (safe: only reached after every table that
    # used them is already gone above).
    sa.Enum(name='user_role_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='investor_profile_kyc_status_enum').drop(op.get_bind(), checkfirst=True)
