"""phase2 kyc investor profile extension wallet mapping

Revision ID: 62df032a68f9
Revises: 60429c1b1184
Create Date: 2026-08-21 23:42:52.462987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62df032a68f9'
down_revision: Union[str, None] = '60429c1b1184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_submission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'AUTO_SCREENING', 'MANUAL_REVIEW', 'VERIFIED', 'REJECTED', name='kyc_submission_status_enum'), autoincrement=False, nullable=False),
    sa.Column('legal_name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.Date(), autoincrement=False, nullable=False),
    sa.Column('nationality', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('submitted_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('screening_result', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chain', sa.Enum('ETHEREUM', 'POLYGON', 'PERMISSIONED_DLT', name='wallet_mapping_chain_enum'), autoincrement=False, nullable=False),
    sa.Column('address', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('label', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='wallet_mapping_status_enum'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.Enum('PASSPORT', 'NATIONAL_ID', 'DRIVERS_LICENSE', 'PROOF_OF_ADDRESS', 'SELFIE', name='kyc_document_document_type_enum'), autoincrement=False, nullable=False),
    sa.Column('object_key', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('ocr_result', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['kyc_submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('investor_profile', sa.Column('jurisdiction', sa.String(length=255), autoincrement=False, nullable=True))

    # Manually added -- unlike `op.create_table(...)` above (which auto-emits `CREATE TYPE` for
    # any `sa.Enum` column via SQLAlchemy's DDL events), `op.add_column(...)` against an
    # *existing* table does not: autogenerate happily inlines `sa.Enum(...)` into the
    # `add_column` call below, but running it as-is fails with `UndefinedObjectError: type
    # "investor_profile_investor_type_enum" does not exist` because nothing ever issued the
    # `CREATE TYPE` first. Create both named enum types explicitly before the columns that use
    # them (mirrors the inverse `DROP TYPE` fixup already required in `downgrade()` below).
    investor_type_enum = sa.Enum('INDIVIDUAL', 'INSTITUTIONAL', name='investor_profile_investor_type_enum')
    risk_profile_enum = sa.Enum('CONSERVATIVE', 'MODERATE', 'AGGRESSIVE', name='investor_profile_risk_profile_enum')
    investor_type_enum.create(op.get_bind(), checkfirst=True)
    risk_profile_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('investor_profile', sa.Column('investor_type', investor_type_enum, autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('risk_profile', risk_profile_enum, autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investor_profile', 'risk_profile')
    op.drop_column('investor_profile', 'investor_type')
    op.drop_column('investor_profile', 'jurisdiction')
    op.drop_table('kyc_document')
    op.drop_table('wallet_mapping')
    op.drop_table('kyc_submission')
    # ### end Alembic commands ###

    # Manually added -- see `60429c1b1184_initial_schema.py::downgrade()`'s comment for why
    # autogenerate never emits `DROP TYPE` for Postgres native `ENUM` columns. Every `EnumType`
    # column introduced by this migration's `upgrade()` needs its named enum type dropped here
    # too, or a downgrade-then-upgrade round trip fails with `DuplicateObjectError` on `CREATE
    # TYPE` the second time around.
    sa.Enum(name='kyc_submission_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='wallet_mapping_chain_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='wallet_mapping_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='kyc_document_document_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='investor_profile_investor_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='investor_profile_risk_profile_enum').drop(op.get_bind(), checkfirst=True)
