"""phase5_ledger_funding

Revision ID: 65c6f68a13ab
Revises: bbe9ebae653b
Create Date: 2026-08-22 01:57:49.361989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c6f68a13ab'
down_revision: Union[str, None] = 'bbe9ebae653b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_instruction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_code', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'SGD', 'AED', 'AUD', 'CAD', 'JPY', 'CHF', name='funding_instruction_currency_enum'), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'EXPIRED', name='funding_instruction_status_enum'), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code')
    )
    op.create_table('ledger_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'SGD', 'AED', 'AUD', 'CAD', 'JPY', 'CHF', name='ledger_account_currency_enum'), autoincrement=False, nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('locked_balance', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout_instruction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'SGD', 'AED', 'AUD', 'CAD', 'JPY', 'CHF', name='payout_instruction_currency_enum'), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('RECORDED', name='payout_instruction_status_enum'), autoincrement=False, nullable=False),
    sa.Column('memo', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_type', sa.Enum('CREDIT_FUNDING', 'DEBIT_PAYOUT', name='ledger_entry_entry_type_enum'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'SGD', 'AED', 'AUD', 'CAD', 'JPY', 'CHF', name='ledger_entry_currency_enum'), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('reference_type', sa.Enum('FUNDING_INSTRUCTION', 'PAYOUT_INSTRUCTION', name='ledger_entry_reference_type_enum'), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###

    # -- ★ manually stripped: autogenerate flagged `43b2ddb8875c`'s hand-authored composite FK/
    # UNIQUE/CHECK constraints on `asset`/`custodian` as spurious drift (since `austial.orm`'s
    # entity metadata has no way to express them -- see that migration's own docstring and
    # `alembic/README.md`'s "Gotcha: hand-authored composite constraints will look like drift to
    # autogenerate" section) and generated `drop_constraint`/`create_foreign_key` calls here that
    # would have reverted `asset.custodian_id` to a plain single-column FK, silently deleting the
    # DB-level half of "an asset cannot be tokenized unless its custodian is IFSCA-verified".
    # Removed entirely, per that section's explicit instruction (mirrors
    # `bbe9ebae653b_phase4_issuance_workflow.py`'s identical strip) -- this migration only adds
    # the four new Phase 5 tables, it does not touch `asset`/`custodian` at all.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entry')
    op.drop_table('payout_instruction')
    op.drop_table('ledger_account')
    op.drop_table('funding_instruction')
    # ### end Alembic commands ###

    # Manually added -- see `60429c1b1184_initial_schema.py::downgrade()`'s comment for why
    # autogenerate never emits `DROP TYPE` for Postgres native `ENUM` columns. Every `EnumType`
    # column this migration's `upgrade()` introduced needs its named enum type dropped here too.
    sa.Enum(name='funding_instruction_currency_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='funding_instruction_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ledger_account_currency_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='payout_instruction_currency_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='payout_instruction_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ledger_entry_entry_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ledger_entry_currency_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ledger_entry_reference_type_enum').drop(op.get_bind(), checkfirst=True)
