"""phase2 kyc risk disclosure consent

Revision ID: 9da67ca9bb72
Revises: 62df032a68f9
Create Date: 2026-08-21 23:57:00.741921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da67ca9bb72'
down_revision: Union[str, None] = '62df032a68f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_disclosure_consent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disclosure_version', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['kyc_submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_disclosure_consent')
    # ### end Alembic commands ###
