"""phase4 issuance workflow

Revision ID: bbe9ebae653b
Revises: 43b2ddb8875c
Create Date: 2026-08-22 00:56:07.298769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe9ebae653b'
down_revision: Union[str, None] = '43b2ddb8875c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_contract_deployment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bytecode_hash', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('audit_report_ref', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('deployed_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokenization_proposal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_units', sa.Numeric(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('unit_price_usd', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('min_subscription_units', sa.Numeric(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('subscription_start_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('subscription_end_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'DOCUMENTATION_REVIEW', 'COMPLIANCE_APPROVED', 'IFSCA_FILED', 'IFSCA_APPROVED', 'LAUNCHED', 'REJECTED', name='tokenization_proposal_status_enum'), autoincrement=False, nullable=False),
    sa.Column('ifsca_filing_reference', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('ifsca_approval_reference', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disclosure_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disclosure_type', sa.Enum('RISK', 'FEE', 'LIQUIDITY', 'CUSTODY', 'TAX', 'PROSPECTUS', name='disclosure_document_disclosure_type_enum'), autoincrement=False, nullable=False),
    sa.Column('object_key', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_current', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['tokenization_proposal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('total_supply', sa.Numeric(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('contract_address', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('paused', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('launched_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('smart_contract_deployment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['tokenization_proposal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smart_contract_deployment_id'], ['smart_contract_deployment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###

    # -- ★ manually stripped: autogenerate flagged `43b2ddb8875c`'s hand-authored composite FK/
    # UNIQUE/CHECK constraints on `asset`/`custodian` as spurious drift (since `austial.orm`'s
    # entity metadata has no way to express them -- see that migration's own docstring and
    # `alembic/README.md`'s "Gotcha: hand-authored composite constraints will look like drift to
    # autogenerate" section) and generated `drop_constraint`/`create_foreign_key` calls here that
    # would have reverted `asset.custodian_id` to a plain single-column FK, silently deleting the
    # DB-level half of "an asset cannot be tokenized unless its custodian is IFSCA-verified".
    # Removed entirely, per that section's explicit instruction -- this migration only adds the
    # four new Phase 4 tables, it does not touch `asset`/`custodian` at all.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_series')
    op.drop_table('disclosure_document')
    op.drop_table('tokenization_proposal')
    op.drop_table('smart_contract_deployment')
    # ### end Alembic commands ###

    # Manually added -- see `60429c1b1184_initial_schema.py::downgrade()`'s comment for why
    # autogenerate never emits `DROP TYPE` for Postgres native `ENUM` columns. Every `EnumType`
    # column this migration's `upgrade()` introduced needs its named enum type dropped here too.
    sa.Enum(name='tokenization_proposal_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='disclosure_document_disclosure_type_enum').drop(op.get_bind(), checkfirst=True)
