"""phase7_valuation_redemptions_distributions

Revision ID: ee5100495913
Revises: ff51a5f702b5
Create Date: 2026-08-22 04:08:45.102109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5100495913'
down_revision: Union[str, None] = 'ff51a5f702b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'SGD', 'AED', 'AUD', 'CAD', 'JPY', 'CHF', name='distribution_currency_enum'), autoincrement=False, nullable=False),
    sa.Column('record_date', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', name='distribution_status_enum'), autoincrement=False, nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('processed_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('token_series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token_series_id'], ['token_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_feed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nav_per_unit', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('anomaly_score', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'QUARANTINED', name='valuation_feed_status_enum'), autoincrement=False, nullable=False),
    sa.Column('reported_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('token_series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token_series_id'], ['token_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redemption_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('units_requested', sa.Numeric(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('nav_per_unit_snapshot', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('payout_amount', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'COMPLIANCE_APPROVED', 'CUSTODIAN_RELEASED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='redemption_request_status_enum'), autoincrement=False, nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('payout_instruction_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('processed_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['token_holding.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Manually added -- `LedgerEntry.LEDGER_ENTRY_TYPES`/`LEDGER_ENTRY_REFERENCE_TYPES` gained
    # `CREDIT_REDEMPTION`/`CREDIT_DISTRIBUTION` and `REDEMPTION`/`DISTRIBUTION` this phase (see
    # that entity's docstring), but autogenerate does not diff Postgres native `ENUM` value sets
    # on an *existing* column/type -- only `CREATE TYPE`/`DROP TYPE`/column adds are detected --
    # so the new values never showed up in the autogenerated diff above and must be added
    # explicitly, same fix-up as `ff51a5f702b5`'s `DEBIT_SUBSCRIPTION_SETTLEMENT`/`SUBSCRIPTION`.
    op.execute("ALTER TYPE ledger_entry_entry_type_enum ADD VALUE IF NOT EXISTS 'CREDIT_REDEMPTION'")
    op.execute("ALTER TYPE ledger_entry_entry_type_enum ADD VALUE IF NOT EXISTS 'CREDIT_DISTRIBUTION'")
    op.execute("ALTER TYPE ledger_entry_reference_type_enum ADD VALUE IF NOT EXISTS 'REDEMPTION'")
    op.execute("ALTER TYPE ledger_entry_reference_type_enum ADD VALUE IF NOT EXISTS 'DISTRIBUTION'")

    # `op.drop_constraint(...'fk_asset_custodian_verified'...)` / `op.create_foreign_key(...)` /
    # `op.drop_constraint(...'ck_asset_custodian_verified_when_attached'...)` /
    # `op.drop_constraint(...'uq_custodian_id_ifsca_verified'...)` autogenerate wanted to emit here
    # were stripped -- these are the hand-authored `asset`/`custodian` composite
    # unique/FK/CHECK constraints from `43b2ddb8875c_phase3_issuers_custodians_assets.py` that
    # `austial.orm`'s entity metadata has no way to express, so autogenerate always misreads them
    # as spurious drift. See `alembic/README.md`'s "Gotcha: hand-authored composite constraints"
    # section -- do not let autogenerate revert them. This migration only adds the three new
    # Phase 7 tables, it does not touch `asset`/`custodian` at all.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redemption_request')
    op.drop_table('valuation_feed')
    op.drop_table('distribution')
    # ### end Alembic commands ###

    # Manually added -- see `60429c1b1184_initial_schema.py::downgrade()`'s identical fix-up for
    # why autogenerate never emits `DROP TYPE` for named enum columns on Postgres.
    sa.Enum(name='distribution_currency_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='distribution_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='valuation_feed_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='redemption_request_status_enum').drop(op.get_bind(), checkfirst=True)

    # Note: the `CREDIT_REDEMPTION`/`CREDIT_DISTRIBUTION`/`REDEMPTION`/`DISTRIBUTION` values added
    # to `ledger_entry_entry_type_enum`/`ledger_entry_reference_type_enum` in `upgrade()` are
    # deliberately *not* removed here -- Postgres has no `ALTER TYPE ... DROP VALUE`; removing an
    # enum value requires rebuilding the type (rename, recreate, migrate every dependent column,
    # drop the old type), which is unsafe to do generically in a downgrade that doesn't know
    # whether any `ledger_entry` row already uses the value. Left in place; harmless on an unused
    # value.
