"""phase6_subscription_allocation

Revision ID: ff51a5f702b5
Revises: 65c6f68a13ab
Create Date: 2026-08-22 02:23:05.256499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff51a5f702b5'
down_revision: Union[str, None] = '65c6f68a13ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('units', sa.Numeric(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('allocated_units', sa.Numeric(precision=28, scale=8), autoincrement=False, nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FUNDED', 'CONFIRMED', 'ALLOCATED', 'REFUNDED', 'CANCELLED', name='subscription_status_enum'), autoincrement=False, nullable=False),
    sa.Column('risk_disclosure_accepted', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('fee_disclosure_accepted', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('disclosures_acknowledged_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('processed_by_user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('token_series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_series_id'], ['token_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_holding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('avg_cost_usd', sa.Numeric(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'REDEEMED', name='token_holding_status_enum'), autoincrement=False, nullable=False),
    sa.Column('custodian_confirmation_ref', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('token_series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_series_id'], ['token_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Manually added -- `LedgerEntry.LEDGER_ENTRY_TYPES`/`LEDGER_ENTRY_REFERENCE_TYPES` gained
    # `DEBIT_SUBSCRIPTION_SETTLEMENT`/`SUBSCRIPTION` this phase (see that entity's docstring), but
    # autogenerate does not diff Postgres native `ENUM` value sets on an *existing* column/type --
    # only `CREATE TYPE`/`DROP TYPE`/column adds are detected -- so the new values never showed up
    # in the autogenerated diff above and must be added explicitly.
    op.execute("ALTER TYPE ledger_entry_entry_type_enum ADD VALUE IF NOT EXISTS 'DEBIT_SUBSCRIPTION_SETTLEMENT'")
    op.execute("ALTER TYPE ledger_entry_reference_type_enum ADD VALUE IF NOT EXISTS 'SUBSCRIPTION'")

    # `op.drop_constraint(...'fk_asset_custodian_verified'...)` / `op.create_foreign_key(...)` /
    # `op.drop_constraint(...'ck_asset_custodian_verified_when_attached'...)` /
    # `op.drop_constraint(...'uq_custodian_id_ifsca_verified'...)` autogenerate wanted to emit here
    # were stripped -- these are the hand-authored `asset`/`custodian` composite
    # unique/FK/CHECK constraints from `43b2ddb8875c_phase3_issuers_custodians_assets.py` that
    # `austial.orm`'s entity metadata has no way to express, so autogenerate always misreads them
    # as spurious drift. See `alembic/README.md`'s "Gotcha: hand-authored composite constraints"
    # section -- do not let autogenerate revert them.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_holding')
    op.drop_table('subscription')
    # ### end Alembic commands ###

    # Manually added -- see `60429c1b1184_initial_schema.py::downgrade()`'s identical fix-up for
    # why autogenerate never emits `DROP TYPE` for named enum columns on Postgres.
    sa.Enum(name='subscription_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='token_holding_status_enum').drop(op.get_bind(), checkfirst=True)

    # Note: the `DEBIT_SUBSCRIPTION_SETTLEMENT`/`SUBSCRIPTION` values added to
    # `ledger_entry_entry_type_enum`/`ledger_entry_reference_type_enum` in `upgrade()` are
    # deliberately *not* removed here -- Postgres has no `ALTER TYPE ... DROP VALUE`; removing an
    # enum value requires rebuilding the type (rename, recreate, migrate every dependent column,
    # drop the old type), which is unsafe to do generically in a downgrade that doesn't know
    # whether any `ledger_entry` row already uses the value. Left in place; harmless on an unused
    # value.
