variable "aws_profile" {
  description = "AWS CLI profile to use for every resource in this stack."
  type        = string
  default     = "aayush-gift"
}

variable "aws_region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "us-east-1"
}

variable "project" {
  description = "Short project name used to prefix/name resources."
  type        = string
  default     = "austial"
}

variable "environment" {
  description = "Deployment environment tag."
  type        = string
  default     = "demo"
}

variable "instance_type" {
  description = "EC2 instance type for the backend host. Kept at t3.micro (free-tier eligible) per cost constraints."
  type        = string
  default     = "t3.micro"
}

variable "db_instance_class" {
  description = "RDS instance class. Kept at db.t3.micro per cost constraints."
  type        = string
  default     = "db.t3.micro"
}

variable "db_allocated_storage" {
  description = "RDS storage size in GB."
  type        = number
  default     = 20
}

variable "db_name" {
  description = "Initial database name."
  type        = string
  default     = "swadely"
}

variable "db_username" {
  description = "Master username for RDS."
  type        = string
  default     = "swadely"
}

variable "db_password" {
  description = "Master password for RDS. Passed in via TF_VAR_db_password / terraform.tfvars, not committed."
  type        = string
  sensitive   = true
}

variable "app_port" {
  description = "Port the backend container listens on."
  type        = number
  default     = 8000
}

variable "ecr_repository_name" {
  description = "Name of the ECR repository for the backend image."
  type        = string
  default     = "austial-backend"
}

variable "container_image_tag" {
  description = "Tag of the backend image to run. Updated after the first `docker push`; user-data pulls this tag on boot."
  type        = string
  default     = "latest"
}

variable "api_key" {
  description = "Value for the app's API_KEY env var (used by the protected health route)."
  type        = string
  sensitive   = true
  default     = "changeme"
}

# --- Phase 1 additions: auth (JWT) + object storage --------------------------

# JWT_SECRET itself is no longer a variable -- it's generated by the `random_password.jwt_secret`
# resource in main.tf (a Terraform-managed random secret, not a hand-picked literal sourced from
# terraform.tfvars). See that resource's comment for why.

variable "jwt_access_token_ttl_minutes" {
  description = "Value for the app's JWT_ACCESS_TOKEN_TTL_MINUTES env var. Matches the app's own default (15) -- set explicitly here so infra doesn't silently rely on an app-side default drifting."
  type        = number
  default     = 15
}

variable "jwt_refresh_token_ttl_days" {
  description = "Value for the app's JWT_REFRESH_TOKEN_TTL_DAYS env var. Matches the app's own default (30)."
  type        = number
  default     = 30
}

# --- Phase 5 additions: ledger funding beneficiary display details -----------

# Static wire/beneficiary details `LedgerService` shows investors on every `FundingInstruction`
# (see `backend/src/modules/ledger/ledger_service.py`) -- same for every instruction, differs only
# per deployment environment, so config-driven rather than hardcoded. Demo values only, not a real
# bank account; not marked `sensitive` since they're meant to be displayed back to investors.

variable "ledger_beneficiary_name" {
  description = "Value for the app's LEDGER_BENEFICIARY_NAME env var -- demo wire beneficiary display name."
  type        = string
  default     = "Swadely Demo Custody Account"
}

variable "ledger_beneficiary_bank_name" {
  description = "Value for the app's LEDGER_BENEFICIARY_BANK_NAME env var -- demo wire beneficiary bank name."
  type        = string
  default     = "GIFT City Demo Bank"
}

variable "ledger_beneficiary_account_number" {
  description = "Value for the app's LEDGER_BENEFICIARY_ACCOUNT_NUMBER env var -- demo wire account number, not a real account."
  type        = string
  default     = "000123456789"
}

variable "ledger_beneficiary_swift_bic" {
  description = "Value for the app's LEDGER_BENEFICIARY_SWIFT_BIC env var -- demo SWIFT/BIC code."
  type        = string
  default     = "GIFTINBBDEM"
}

# --- OTP module additions: development mode + fixed OTP config ---------------

variable "development_mode" {
  description = "Value for the app's DEVELOPMENT_MODE env var. When 'true', OTP generation uses a fixed code (FIXED_OTP_CODE) instead of random, for easier testing."
  type        = string
  default     = "true"
}

variable "fixed_otp_code" {
  description = "Value for the app's FIXED_OTP_CODE env var -- the hardcoded OTP used when DEVELOPMENT_MODE=true."
  type        = string
  default     = "123456"
}

variable "otp_length" {
  description = "Value for the app's OTP_LENGTH env var -- number of digits in generated OTP codes."
  type        = number
  default     = 6
}

variable "otp_ttl_minutes" {
  description = "Value for the app's OTP_TTL_MINUTES env var -- how long an OTP remains valid."
  type        = number
  default     = 10
}

variable "otp_max_attempts" {
  description = "Value for the app's OTP_MAX_ATTEMPTS env var -- max verification attempts before an OTP is invalidated."
  type        = number
  default     = 3
}
